update resynthesizer heal selection plugin to work with recent 2.99 release
bootchk/resynthesizer pull request #136
Opened 2024-11-14 15:34 UTC by WarpspeedSCP

2024-11-14 16:22 UTC, Artturin commented on PluginScripts/plugin-heal-selection.py
> +#!/usr/bin/python3
```suggestion
#!/usr/bin/env python3
```

Python doesn't have to be there but can still be in $PATH

2024-11-14 16:37 UTC, WarpspeedSCP commented on PluginScripts/plugin-heal-selection.py
> +#!/usr/bin/python3
Oops!

2024-11-14 17:21 UTC, lilydjwg commented on PluginScripts/plugin-heal-selection.py
> +#!/usr/bin/python3
But wIth `env` it may find the wrong Python, e.g. in venvs where there are no `gi` package.

2024-11-15 01:50 UTC, lilydjwg commented on PluginScripts/plugin-heal-selection.py
> +#!/usr/bin/python3
Sometimes I just forgot I'm in a venv, and installed applications shouldn't break in a venv. People don't need to know if an application uses Python to use an application.

It is common to use `env python3` but it doesn't mean it is standard.

[PEP 394](https://peps.python.org/pep-0394/) says:

> For scripts that are only expected to be run in an activated virtual environment, shebang lines can be written as #!/usr/bin/env python, as this instructs the script to respect the active virtual environment.

This script uses `gi` which is uncommon to use in a venv, so it's more likely a system Python home should be used. That's `/usr/bin/python` on Linux. The shebang can be updated in the installation process, and various Python packaging systems do this.

2024-11-15 04:09 UTC, WarpspeedSCP commented
This probably wont work with 3.0 RC as is; Im still trying to figure out why the gobject code is failing to compile.

2024-11-15 04:14 UTC, Artturin commented on PluginScripts/plugin-heal-selection.py
> +#!/usr/bin/python3
In NixOS where we don't have binaries in /usr/bin/ other than env, we patch the shebangs with the correct python env anyways so both versions work for us.

@WarpspeedSCP you can revert my suggestion.

2024-11-15 08:17 UTC, WarpspeedSCP commented on PluginScripts/plugin-heal-selection.py
> +#!/usr/bin/python3
done.

2024-11-15 08:18 UTC, WarpspeedSCP commented
I've managed to get the plugin working with the latest 3.0 build on my machine, could anybody try compiling it to verify?

2024-11-15 08:21 UTC, WarpspeedSCP commented on PluginScripts/plugin-heal-selection.py
> +            procedure.add_choice_argument ("directionParam", _("Direct_ion"), _("Sampling direction"),
```suggestion
            procedure.add_choice_argument ("directionParam", _("Direct_ion"), _("Where to sample pixels from"),
```

2024-11-15 08:21 UTC, WarpspeedSCP commented on PluginScripts/plugin-heal-selection.py
> +            procedure.add_choice_argument ("orderParam", _("Order"), _("Fill order"),
```suggestion
            procedure.add_choice_argument ("orderParam", _("Order"), _("The order to fill the selection in"),
```

2024-11-15 08:22 UTC, WarpspeedSCP commented on PluginScripts/plugin-heal-selection.py
> +    }
this isn't needed anymore.
```suggestion
```

2024-11-15 09:39 UTC, lilydjwg commented
I can't build it with gimp 3.0.0-RC1+git:

<details>

```
make  all-recursive
make[1]: Entering directory '/ldata/src/resynthesizer'
Making all in lib
make[2]: Entering directory '/ldata/src/resynthesizer/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/ldata/src/resynthesizer/lib'
Making all in src
make[2]: Entering directory '/ldata/src/resynthesizer/src'
Making all in resynthesizer
make[3]: Entering directory '/ldata/src/resynthesizer/src/resynthesizer'
gcc -DHAVE_CONFIG_H -I. -I../..  -DLOCALEDIR=\""/usr/local/share/locale"\" -DDATADIR=\""/usr/local/share/resynthesizer"\" -I../.. -I/usr/include/gimp-3.0 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/atk-1.0 -I/usr/include/gegl-0.4 -I/usr/include/json-glib-1.0 -I/usr/include/babl-0.1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/sysprof-6 -pthread -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/cloudproviders -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/local/include -I./../../lib -DG_DISABLE_DEPRECATED -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED -DGIMP_DISABLE_DEPRECATED  -g -O2 -Wall -MT resynthesizer-plugin.o -MD -MP -MF .deps/resynthesizer-plugin.Tpo -c -o resynthesizer-plugin.o `test -f 'plugin.c' || echo './'`plugin.c
plugin.c:37:9: error: unknown type name ‘GimpParam’; did you mean ‘GimpPath’?
   37 |         GimpParam * param,
      |         ^~~~~~~~~
      |         GimpPath
plugin.c:39:9: error: unknown type name ‘GimpParam’; did you mean ‘GimpPath’?
   39 |         GimpParam **      return_vals)   // OUT
      |         ^~~~~~~~~
      |         GimpPath
In file included from plugin.c:91:
resynthPDBv2.h: In function ‘query’:
resynthPDBv2.h:27:3: error: unknown type name ‘GimpParamDef’; did you mean ‘GimpParasite’?
   27 |   GimpParamDef *return_vals = NULL;
      |   ^~~~~~~~~~~~
      |   GimpParasite
resynthPDBv2.h:28:23: error: ‘resynth_paramdefs’ undeclared (first use in this function)
   28 |   gint nargs = sizeof(resynth_paramdefs)/sizeof(resynth_paramdefs[0]);
      |                       ^~~~~~~~~~~~~~~~~
resynthPDBv2.h:28:23: note: each undeclared identifier is reported only once for each function it appears in
resynthPDBv2.h:33:3: error: implicit declaration of function ‘gimp_install_procedure’ [-Wimplicit-function-declaration]
   33 |   gimp_install_procedure(
      |   ^~~~~~~~~~~~~~~~~~~~~~
resynthPDBv2.h:42:11: error: ‘GIMP_PLUGIN’ undeclared (first use in this function); did you mean ‘GIMP_PLUG_IN’?
   42 |           GIMP_PLUGIN,
      |           ^~~~~~~~~~~
      |           GIMP_PLUG_IN
resynthPDBv2.h: At top level:
resynthPDBv2.h:48:8: error: unknown type name ‘GimpPlugInInfo’; did you mean ‘GimpPlugIn’?
   48 | static GimpPlugInInfo PLUG_IN_INFO = {
      |        ^~~~~~~~~~~~~~
      |        GimpPlugIn
resynthPDBv2.h:49:3: error: initialization of ‘int’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
   49 |   NULL, /* init_proc */
      |   ^~~~
resynthPDBv2.h:49:3: note: (near initialization for ‘PLUG_IN_INFO’)
resynthPDBv2.h:50:3: warning: excess elements in scalar initializer
   50 |   NULL, /* quit_proc */
      |   ^~~~
resynthPDBv2.h:50:3: note: (near initialization for ‘PLUG_IN_INFO’)
resynthPDBv2.h:51:3: warning: excess elements in scalar initializer
   51 |   query, /* query_proc */
      |   ^~~~~
resynthPDBv2.h:51:3: note: (near initialization for ‘PLUG_IN_INFO’)
resynthPDBv2.h:52:3: error: ‘run’ undeclared here (not in a function); did you mean ‘trunc’?
   52 |   run, /* run_proc */
      |   ^~~
      |   trunc
resynthPDBv2.h:52:3: warning: excess elements in scalar initializer
resynthPDBv2.h:52:3: note: (near initialization for ‘PLUG_IN_INFO’)
resynthPDBv2.h:57:1: error: return type defaults to ‘int’ [-Wimplicit-int]
   57 | MAIN()
      | ^~~~
plugin.c: In function ‘MAIN’:
plugin.c:105: error: expected ‘{’ at end of input
plugin.c:105: warning: control reaches end of non-void function [-Wreturn-type]
resynthPDBv2.h: At top level:
resynthPDBv2.h:48:23: warning: ‘PLUG_IN_INFO’ defined but not used [-Wunused-variable]
   48 | static GimpPlugInInfo PLUG_IN_INFO = {
      |                       ^~~~~~~~~~~~
make[3]: *** [Makefile:462: resynthesizer-plugin.o] Error 1
make[3]: Leaving directory '/ldata/src/resynthesizer/src/resynthesizer'
make[2]: *** [Makefile:355: all-recursive] Error 1
make[2]: Leaving directory '/ldata/src/resynthesizer/src'
make[1]: *** [Makefile:411: all-recursive] Error 1
make[1]: Leaving directory '/ldata/src/resynthesizer'
make: *** [Makefile:352: all] Error 2
```
</details>

2024-11-15 11:54 UTC, WarpspeedSCP commented
I did encounter something similar before. Can you check the values of the gimp major and minor versions? I added a few checks that section off the ui and gimp 2 related code but maybe I missed some parts.

2024-11-15 11:58 UTC, WarpspeedSCP commented
Oh, oops. I didn't commit certain changes. Fastforward and try again please!

2024-11-15 14:15 UTC, lilydjwg commented
It compiles, but the installation seems wrong. GIMP 3 says plugins should be put in subdirectories inside the plugin-ins directory. It turns out the subdirectory name needs to match the filename too.

And then, a lot of `No module named 'gimpfu'` errors.

The "heal selection" plugin loads, but when I run it on a selection near the right border, an error complaining that `new-height` is out of range (-538 or so). It does the expected job though.

There are also error messages that look like memory correuption, e.g.

```
(resynthesizer:2257397): GLib-GObject-CRITICAL **: 22:11:54.967: g_object_get_is_valid_property: object class 'GimpProcedureConfigRun-plug-in-resyn
thesizer' has no property named 'P\u0012\xa7\xa4\x94U'                                                                                             
```

2024-11-15 15:12 UTC, WarpspeedSCP commented
Yeah, the cropping code isnt fully fixed yet. Also, I've only updated the heal selection script at the moment which is why youre seeing the gimpfu errors.

2024-11-15 16:04 UTC, bootchk commented
I am following along.  Ping me more directly (somehow?) if needed.

Thanks

2024-11-15 17:01 UTC, WarpspeedSCP commented
sounds like the way to go. I'm also seeing some very weird results with all around direction and random fill that I need to debug. I think the property problem is likely because I forgot to specify the procedure API correctly.

2024-11-15 18:06 UTC, rautamiekka requested changes
Also:
- the indentations are all over the place.
- function/method names both have and don't have a space before the opening parenthesis.

2024-11-15 18:06 UTC, rautamiekka commented on PluginScripts/plugin-heal-selection.py
> +      targetUpperRightY   = target_bounds[3]
```suggestion
      frisketLowerLeftX, frisketLowerLeftY, frisketUpperRightX, frisketUpperRightY = frisketBounds

      targetLowerLeftX, targetLowerLeftY, targetUpperRightX, targetUpperRightY = target_bounds
```

2024-11-15 18:40 UTC, WarpspeedSCP commented on PluginScripts/plugin-heal-selection.py
> +      targetUpperRightY   = target_bounds[3]
I've used a different method to extract the coords now.

2024-11-15 18:40 UTC, WarpspeedSCP commented on PluginScripts/plugin-heal-selection.py
> +        if (name == PLUGIN_NAME):
fixed now.

2024-11-16 00:44 UTC, rautamiekka approved these changes
LGTM, nothing sticks out as wrong, but that ain't a guarantee.

2024-11-16 08:06 UTC, WarpspeedSCP commented
@lilydjwg can you try using the heal selection plugin with the new changes? You'll need to recompile.

2024-11-16 08:32 UTC, lilydjwg commented
I see no issues except an error message saying `gimp_plug_in_destroy_proxies: ERROR: GimpLayer proxy with ID 4 was refed by plug-in, it MUST NOT do that!` and some logs from `resynthesizer`.

2024-11-16 12:37 UTC, bootchk commented
> Also, note that the current version of the plugin does not in any way attempt to retain the behaviour of the v2 plugin.

??? Is that correct?  Just reading the code, it seems that it retains most of the behaviour, except regarding which selected layers are healed.

Re multi-layer select.  Since that feature was added to GIMP 3, most plugins need to choose a strategy.   I think that indeed the heal plugin should only heal one layer.  I think it should warn if more layers are passed, saying something like "Will only heal the first selected layer." 

But also, if many layers are passed, maybe the heal plugin should use as corpus: the flattened set of passed layers, in a copy.  Because the user may expect to heal as it is visible, and the multiple layers may have a different visual appearance, due to transparency, and even compositing modes?

Some plugins might choose a strategy: iteratively operate on all passed layers.  I haven't given this enough thought, what would it mean to iteratively heal many layers, from which corpuses?

While you are at it, could you please change the attribution of the plugin, from James Henstridge to Paul Harrison?
He is the original author of the plugin.  Henstridge wrote PyGimp, and provided example plugins.
While Paul Harrison probably copied an example from Henstridge, I think that the essential credit belongs to Paul Harrison.You can other names too, as you see fit.

2024-11-16 12:43 UTC, bootchk commented
Also, I see you have touched resynthesizer-gui.c.  That is fine, if just to get it to compile.

But I think it needs a major rewrite OR replace with a Python or ScriptFu plugin.  The C is in Gtk2 and probably needs much work to get to Gtk 3 (and then to Gtk 4 eventually.)  But it is really just a GUI front end to the engine, and could be replaced by a plugin in a higher level language.  (Possibly with minor loss of user-friendliness.)  Which is the plan, see the roadmap.  I can't remember whether I already have a prototype in Python or Scheme.

2024-11-16 13:32 UTC, WarpspeedSCP commented
> ??? Is that correct? Just reading the code, it seems that it retains most of the behaviour, except regarding which selected layers are healed.

Ah, not any more, I think. But I'm still not sure what being considered "active" entails.

Maybe I should include a switch for "merge all visible layers before healing".

> Also, I see you have touched resynthesizer-gui.c.

This was just to add in version guards, simce all that code is meant to work only with gimp 2.

> While you are at it, could you please change the attribution of the plugin, from James Henstridge to Paul Harrison?

Will do. Its just waht happens when you copy paste plugin code, I guess.

2024-11-17 18:27 UTC, Rizzlord commented
sooo, awesome! But how do i try it out? Would love to finally abandon gimp 2.10

2024-11-18 17:39 UTC, WarpspeedSCP commented
It'll take a bit of work (and time), especially on windows. I can try making a windows build at some point, but I have been a bit busy, so it's difficult to say when I can truly do it.

If you'd like to try compilimg it yourself, I believe ypu will need to use mingw and sething like git bash to do so.

2024-11-20 02:28 UTC, WarpspeedSCP commented
I have win10 ready on a vm, I just haven't set up the dev env.

2025-01-23 13:29 UTC, bootchk commented
Unfortunately, I will probably not merge this into the repo.

I have decided to use plugins rewritten in Scheme, for GIMP 3, based on those written by itr-tert for GIMP 2.
The plugins were originally in Scheme (written by the original author, Paul Harrison.)
I ported them to Python long ago, because I knew the language and PythonFu was concise.
IMO the Scheme language is better in this case, more concise.

See the readme News.

If you can convince me that some users will want to install the Python versions, I will consider merging.
But the plan is to install the Scheme plugins.
Until there is evidence that the Python versions are better.

2025-01-23 16:25 UTC, WarpspeedSCP commented
Ahh, all right. I havent had time to work on this more, so perhaps it's just as well. I'll still push to this branch at some point so we can have something feature complete, but I don't mind that this won't be merged. You might want to link this pr somewhere so those who do want python can still find something up to date.

2025-02-28 11:45 UTC, pdalfarr commented
Hi @bootchk
Thanks for this great plugin!

Any news on the "GIMP 3 front"?

Thanks

2026-04-09 15:57 UTC, bootchk commented
Closing.

In the end, I used Scheme plugins from iter-tert instead of Python plugins.

If there is a reason to use Python plugins instead, convince me.
Who knows, in the future GIMP might eliminate ScriptFu,
and then we might need to salvage this PR.

2026-04-09 15:57 UTC, closed without merging